site_name: Data Platform Terraform Modules
site_url: https://daun-gatal.github.io/terraform-modules/
site_author: Rizal M.
site_description: Production-grade Terraform modules for building modern data platforms.

repo_name: daun-gatal/terraform-modules
repo_url: https://github.com/daun-gatal/terraform-modules

theme:
  name: material
  palette:
    # Light Mode
    - scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark Mode
    - scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - content.code.copy
  icon:
    logo: material/terraform
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daun-gatal
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rizal-mahifa

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
