name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docs:
    name: Check READMEs
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render terraform-docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          find-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          fail-on-diff: "true"
