# ===========================================
# OpenBao Configuration
# Generated by Terraform - DO NOT EDIT MANUALLY
# ===========================================

# -------------------------------
# Static Seal Configuration
# See: https://openbao.org/docs/configuration/seal/static/
# -------------------------------
seal "static" {
  current_key_id = "${current_key_id}"
  current_key    = "file:///openbao/secrets/unseal-current.key"
%{ if has_previous_key ~}
  previous_key_id = "${previous_key_id}"
  previous_key    = "file:///openbao/secrets/unseal-previous.key"
%{ endif ~}
}

# -------------------------------
# Storage Backend: ${storage_type}
# -------------------------------
%{ if storage_type == "postgresql" ~}
# See: https://openbao.org/docs/configuration/storage/postgresql/
storage "postgresql" {
  connection_url = "${postgresql.connection_url}"
%{ if postgresql.table != "openbao_kv_store" ~}
  table = "${postgresql.table}"
%{ endif ~}
%{ if postgresql.max_idle_connections != null ~}
  max_idle_connections = ${postgresql.max_idle_connections}
%{ endif ~}
%{ if postgresql.max_parallel != 128 ~}
  max_parallel = "${postgresql.max_parallel}"
%{ endif ~}
%{ if postgresql.ha_enabled ~}
  ha_enabled = "true"
%{ endif ~}
%{ if postgresql.ha_enabled && postgresql.ha_table != "openbao_ha_locks" ~}
  ha_table = "${postgresql.ha_table}"
%{ endif ~}
%{ if postgresql.skip_create_table ~}
  skip_create_table = "true"
%{ endif ~}
%{ if postgresql.max_connect_retries != 1 ~}
  max_connect_retries = ${postgresql.max_connect_retries}
%{ endif ~}
}
%{ endif ~}

%{ if storage_type == "raft" ~}
# See: https://openbao.org/docs/configuration/storage/raft/
storage "raft" {
  path = "${raft.path}"
%{ if raft.node_id != null && raft.node_id != "" ~}
  node_id = "${raft.node_id}"
%{ endif ~}
%{ if raft.performance_multiplier != 0 ~}
  performance_multiplier = ${raft.performance_multiplier}
%{ endif ~}
%{ if raft.trailing_logs != 10000 ~}
  trailing_logs = ${raft.trailing_logs}
%{ endif ~}
%{ if raft.snapshot_threshold != 8192 ~}
  snapshot_threshold = ${raft.snapshot_threshold}
%{ endif ~}
%{ if raft.snapshot_interval != "120s" ~}
  snapshot_interval = "${raft.snapshot_interval}"
%{ endif ~}
%{ if raft.max_entry_size != 1048576 ~}
  max_entry_size = ${raft.max_entry_size}
%{ endif ~}
%{ if raft.max_transaction_size != 8388608 ~}
  max_transaction_size = ${raft.max_transaction_size}
%{ endif ~}
%{ if raft.autopilot_reconcile_interval != "10s" ~}
  autopilot_reconcile_interval = "${raft.autopilot_reconcile_interval}"
%{ endif ~}
%{ if raft.autopilot_update_interval != "2s" ~}
  autopilot_update_interval = "${raft.autopilot_update_interval}"
%{ endif ~}

%{ for join in raft.retry_join ~}
  retry_join {
%{ if join.leader_api_addr != null ~}
    leader_api_addr = "${join.leader_api_addr}"
%{ endif ~}
%{ if join.auto_join != null ~}
    auto_join = "${join.auto_join}"
    auto_join_scheme = "${join.auto_join_scheme}"
    auto_join_port = ${join.auto_join_port}
%{ endif ~}
%{ if join.leader_tls_servername != null ~}
    leader_tls_servername = "${join.leader_tls_servername}"
%{ endif ~}
%{ if join.leader_ca_cert_file != null ~}
    leader_ca_cert_file = "${join.leader_ca_cert_file}"
%{ endif ~}
%{ if join.leader_client_cert_file != null ~}
    leader_client_cert_file = "${join.leader_client_cert_file}"
%{ endif ~}
%{ if join.leader_client_key_file != null ~}
    leader_client_key_file = "${join.leader_client_key_file}"
%{ endif ~}
  }
%{ endfor ~}
}
%{ endif ~}

%{ if storage_type == "file" ~}
# WARNING: File storage is for development only, not recommended for production
storage "file" {
  path = "${file_storage.path}"
}
%{ endif ~}

%{ if length(plugins) > 0 || plugin_auto_download || plugin_auto_register ~}
# -------------------------------
# Plugin Configuration
# See: https://openbao.org/docs/configuration/plugin/
# -------------------------------
plugin_directory         = "${plugin_directory}"
plugin_auto_download     = ${plugin_auto_download}
plugin_auto_register     = ${plugin_auto_register}
plugin_download_behavior = "${plugin_download_behavior}"

%{ for plugin in plugins ~}
plugin "${plugin.name}" {
  image       = "${plugin.image}"
  version     = "${plugin.version}"
  binary_name = "${plugin.binary_name}"
%{ if plugin.sha256sum != "" ~}
  sha256sum   = "${plugin.sha256sum}"
%{ endif ~}
}

%{ endfor ~}
%{ endif ~}
